In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.random.randn(100)

In [4]:
a

array([-0.33202936,  0.39597078,  0.67843909, -0.06378767,  0.03530769,
        0.30804791, -0.308364  , -0.20629126,  0.82351539, -1.09527496,
        0.69022735, -1.05458473,  0.56382315,  0.98149479, -0.6743749 ,
       -0.32790428,  0.86008969, -1.31973463,  0.75622934, -0.73014266,
        0.2490211 , -0.15880053,  1.22867647, -0.85886945,  0.48604526,
       -0.31597759,  0.36197636, -0.98723638, -0.14183023, -0.84274712,
        0.21192264,  0.36056801,  1.63054447, -1.32745542,  1.81353496,
        1.44471732,  1.05904599, -1.5133278 , -0.35279354,  0.25059744,
        0.20315127, -0.02714996, -1.00416991, -0.56722015,  1.82731089,
        0.75422435,  0.06086155,  0.00545753,  0.13287636,  0.75488253,
        0.05753962, -1.4981349 ,  0.79689321,  0.23541892, -0.552121  ,
        1.24683839,  2.37185056,  0.93046396,  0.16190116,  1.4393163 ,
       -0.4803589 ,  0.04507335, -1.80647123,  1.53227624,  1.09125307,
        1.48338194, -0.41908897,  0.24590782,  0.1038181 , -0.50

In [5]:
a.shape      #查看a的維度和陣列

(100,)

In [7]:
a.shape = (5,20)

In [8]:
a

array([[-0.33202936,  0.39597078,  0.67843909, -0.06378767,  0.03530769,
         0.30804791, -0.308364  , -0.20629126,  0.82351539, -1.09527496,
         0.69022735, -1.05458473,  0.56382315,  0.98149479, -0.6743749 ,
        -0.32790428,  0.86008969, -1.31973463,  0.75622934, -0.73014266],
       [ 0.2490211 , -0.15880053,  1.22867647, -0.85886945,  0.48604526,
        -0.31597759,  0.36197636, -0.98723638, -0.14183023, -0.84274712,
         0.21192264,  0.36056801,  1.63054447, -1.32745542,  1.81353496,
         1.44471732,  1.05904599, -1.5133278 , -0.35279354,  0.25059744],
       [ 0.20315127, -0.02714996, -1.00416991, -0.56722015,  1.82731089,
         0.75422435,  0.06086155,  0.00545753,  0.13287636,  0.75488253,
         0.05753962, -1.4981349 ,  0.79689321,  0.23541892, -0.552121  ,
         1.24683839,  2.37185056,  0.93046396,  0.16190116,  1.4393163 ],
       [-0.4803589 ,  0.04507335, -1.80647123,  1.53227624,  1.09125307,
         1.48338194, -0.41908897,  0.24590782,  

In [10]:
a.reshape(100,1)

array([[-0.33202936],
       [ 0.39597078],
       [ 0.67843909],
       [-0.06378767],
       [ 0.03530769],
       [ 0.30804791],
       [-0.308364  ],
       [-0.20629126],
       [ 0.82351539],
       [-1.09527496],
       [ 0.69022735],
       [-1.05458473],
       [ 0.56382315],
       [ 0.98149479],
       [-0.6743749 ],
       [-0.32790428],
       [ 0.86008969],
       [-1.31973463],
       [ 0.75622934],
       [-0.73014266],
       [ 0.2490211 ],
       [-0.15880053],
       [ 1.22867647],
       [-0.85886945],
       [ 0.48604526],
       [-0.31597759],
       [ 0.36197636],
       [-0.98723638],
       [-0.14183023],
       [-0.84274712],
       [ 0.21192264],
       [ 0.36056801],
       [ 1.63054447],
       [-1.32745542],
       [ 1.81353496],
       [ 1.44471732],
       [ 1.05904599],
       [-1.5133278 ],
       [-0.35279354],
       [ 0.25059744],
       [ 0.20315127],
       [-0.02714996],
       [-1.00416991],
       [-0.56722015],
       [ 1.82731089],
       [ 0

In [ ]:
ㄅㄢ