# 來算成績囉

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
grades = np.array([85,70,82])

In [3]:
weights = np.array([0.3,0.4,0.3])

In [4]:
g= grades * weights
g

array([25.5, 28. , 24.6])

In [5]:
g.sum()

78.1

In [7]:
np.dot(grades,weights)       #np.dot(array1,array2) 直接將兩陣列做內積

78.1

# 算全班成績~

In [8]:
grades = np.array([[85,70,82],[75,92,85],[66,67,65],[87,94,60]])

In [9]:
weights = np.array([0.3,0.4,0.3])

In [10]:
np.dot(grades,weights)

array([78.1, 84.8, 66.1, 81.7])

In [12]:
L = np.array([3,5,7,9])

In [13]:
L* 3

array([ 9, 15, 21, 27])